version: '3.8'

services:
  # API Gateway
  gateway:
    build:
      context: ./Gateway/InternetCafe.Gateway
    ports:
      - "5000:80"
    depends_on:
      - auth-user-service
      - computer-session-service
      - account-statistics-service
    networks:
      - internetcafe-network

  # Auth & User Service  
  auth-user-service:
    build:
      context: ./Services/AuthUserService
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=InternetCafe_UserDb;User Id=sa;Password=YourStrongPassword!;TrustServerCertificate=True
    depends_on:
      - sql-server
    networks:
      - internetcafe-network

  # Computer & Session Service
  computer-session-service:
    build:
      context: ./Services/ComputerSessionService
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=InternetCafe_ComputerSessionDb;User Id=sa;Password=YourStrongPassword!;TrustServerCertificate=True
      - ServiceUrls__AuthUserService=http://auth-user-service
      - ServiceUrls__AccountStatisticsService=http://account-statistics-service
    depends_on:
      - sql-server
      - auth-user-service
      - rabbitmq
    networks:
      - internetcafe-network

  # Account & Statistics Service
  account-statistics-service:
    build:
      context: ./Services/AccountStatisticsService
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=InternetCafe_AccountStatsDb;User Id=sa;Password=YourStrongPassword!;TrustServerCertificate=True
      - ServiceUrls__AuthUserService=http://auth-user-service
      - ServiceUrls__ComputerSessionService=http://computer-session-service
    depends_on:
      - sql-server
      - auth-user-service
      - rabbitmq
    networks:
      - internetcafe-network

  # SQL Server
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - internetcafe-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internetcafe-network

networks:
  internetcafe-network:

volumes:
  sqlserver-data: